version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_USER: madhva
      POSTGRES_PASSWORD: password
      POSTGRES_DB: incident_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
